version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./server/.env.dev
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - data:/var/lib/postgres/data

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.dev
    depends_on:
      - postgres

volumes:
  data:
  logs:
